/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AssignmentType = IDL.Variant({
  'assignment' : IDL.Null,
  'exam' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const AssignmentId = IDL.Nat;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'completedAt' : IDL.Opt(Timestamp),
  'title' : IDL.Text,
  'assignmentType' : AssignmentType,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'subjectId' : SubjectId,
  'priority' : Priority,
  'totalMinutesStudied' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const ClassId = IDL.Nat;
export const ScheduledClass = IDL.Record({
  'id' : ClassId,
  'startTime' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'subjectId' : SubjectId,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const SessionId = IDL.Nat;
export const PomodoroSession = IDL.Record({
  'id' : SessionId,
  'completedAt' : Timestamp,
  'durationMinutes' : IDL.Nat,
  'assignmentId' : IDL.Opt(AssignmentId),
  'subjectId' : IDL.Opt(SubjectId),
});
export const StudyStats = IDL.Record({
  'completionRatePercent' : IDL.Nat,
  'totalMinutesThisWeek' : IDL.Nat,
  'sessionsToday' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAssignment' : IDL.Func(
      [SubjectId, IDL.Text, IDL.Text, Timestamp, AssignmentType, Priority],
      [Assignment],
      [],
    ),
  'createScheduledClass' : IDL.Func(
      [SubjectId, IDL.Nat, IDL.Text, IDL.Nat],
      [ScheduledClass],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text], [Subject], []),
  'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
  'deleteScheduledClass' : IDL.Func([ClassId], [IDL.Bool], []),
  'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
  'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getPomodoroSessions' : IDL.Func([], [IDL.Vec(PomodoroSession)], ['query']),
  'getScheduledClasses' : IDL.Func([], [IDL.Vec(ScheduledClass)], ['query']),
  'getStudyStats' : IDL.Func([], [StudyStats], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'logPomodoroSession' : IDL.Func(
      [IDL.Opt(SubjectId), IDL.Opt(AssignmentId), IDL.Nat],
      [PomodoroSession],
      [],
    ),
  'markAssignmentComplete' : IDL.Func([AssignmentId], [IDL.Bool], []),
  'updateAssignment' : IDL.Func(
      [AssignmentId, IDL.Text, IDL.Text, Timestamp, AssignmentType, Priority],
      [IDL.Bool],
      [],
    ),
  'updateSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AssignmentType = IDL.Variant({
    'assignment' : IDL.Null,
    'exam' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AssignmentId = IDL.Nat;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'completedAt' : IDL.Opt(Timestamp),
    'title' : IDL.Text,
    'assignmentType' : AssignmentType,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'subjectId' : SubjectId,
    'priority' : Priority,
    'totalMinutesStudied' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const ClassId = IDL.Nat;
  const ScheduledClass = IDL.Record({
    'id' : ClassId,
    'startTime' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'subjectId' : SubjectId,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const SessionId = IDL.Nat;
  const PomodoroSession = IDL.Record({
    'id' : SessionId,
    'completedAt' : Timestamp,
    'durationMinutes' : IDL.Nat,
    'assignmentId' : IDL.Opt(AssignmentId),
    'subjectId' : IDL.Opt(SubjectId),
  });
  const StudyStats = IDL.Record({
    'completionRatePercent' : IDL.Nat,
    'totalMinutesThisWeek' : IDL.Nat,
    'sessionsToday' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAssignment' : IDL.Func(
        [SubjectId, IDL.Text, IDL.Text, Timestamp, AssignmentType, Priority],
        [Assignment],
        [],
      ),
    'createScheduledClass' : IDL.Func(
        [SubjectId, IDL.Nat, IDL.Text, IDL.Nat],
        [ScheduledClass],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text], [Subject], []),
    'deleteAssignment' : IDL.Func([AssignmentId], [IDL.Bool], []),
    'deleteScheduledClass' : IDL.Func([ClassId], [IDL.Bool], []),
    'deleteSubject' : IDL.Func([SubjectId], [IDL.Bool], []),
    'getAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getPomodoroSessions' : IDL.Func([], [IDL.Vec(PomodoroSession)], ['query']),
    'getScheduledClasses' : IDL.Func([], [IDL.Vec(ScheduledClass)], ['query']),
    'getStudyStats' : IDL.Func([], [StudyStats], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'logPomodoroSession' : IDL.Func(
        [IDL.Opt(SubjectId), IDL.Opt(AssignmentId), IDL.Nat],
        [PomodoroSession],
        [],
      ),
    'markAssignmentComplete' : IDL.Func([AssignmentId], [IDL.Bool], []),
    'updateAssignment' : IDL.Func(
        [AssignmentId, IDL.Text, IDL.Text, Timestamp, AssignmentType, Priority],
        [IDL.Bool],
        [],
      ),
    'updateSubject' : IDL.Func([SubjectId, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };