/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assignment {
  'id' : AssignmentId,
  'completedAt' : [] | [Timestamp],
  'title' : string,
  'assignmentType' : AssignmentType,
  'description' : string,
  'deadline' : Timestamp,
  'subjectId' : SubjectId,
  'priority' : Priority,
  'totalMinutesStudied' : bigint,
  'isComplete' : boolean,
}
export type AssignmentId = bigint;
export type AssignmentType = { 'assignment' : null } |
  { 'exam' : null };
export type ClassId = bigint;
export interface PomodoroSession {
  'id' : SessionId,
  'completedAt' : Timestamp,
  'durationMinutes' : bigint,
  'assignmentId' : [] | [AssignmentId],
  'subjectId' : [] | [SubjectId],
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ScheduledClass {
  'id' : ClassId,
  'startTime' : string,
  'dayOfWeek' : bigint,
  'durationMinutes' : bigint,
  'subjectId' : SubjectId,
}
export type SessionId = bigint;
export interface StudyStats {
  'completionRatePercent' : bigint,
  'totalMinutesThisWeek' : bigint,
  'sessionsToday' : bigint,
}
export interface Subject { 'id' : SubjectId, 'name' : string, 'color' : string }
export type SubjectId = bigint;
export type Timestamp = bigint;
export interface _SERVICE {
  'createAssignment' : ActorMethod<
    [SubjectId, string, string, Timestamp, AssignmentType, Priority],
    Assignment
  >,
  'createScheduledClass' : ActorMethod<
    [SubjectId, bigint, string, bigint],
    ScheduledClass
  >,
  'createSubject' : ActorMethod<[string, string], Subject>,
  'deleteAssignment' : ActorMethod<[AssignmentId], boolean>,
  'deleteScheduledClass' : ActorMethod<[ClassId], boolean>,
  'deleteSubject' : ActorMethod<[SubjectId], boolean>,
  'getAssignments' : ActorMethod<[], Array<Assignment>>,
  'getPomodoroSessions' : ActorMethod<[], Array<PomodoroSession>>,
  'getScheduledClasses' : ActorMethod<[], Array<ScheduledClass>>,
  'getStudyStats' : ActorMethod<[], StudyStats>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'logPomodoroSession' : ActorMethod<
    [[] | [SubjectId], [] | [AssignmentId], bigint],
    PomodoroSession
  >,
  'markAssignmentComplete' : ActorMethod<[AssignmentId], boolean>,
  'updateAssignment' : ActorMethod<
    [AssignmentId, string, string, Timestamp, AssignmentType, Priority],
    boolean
  >,
  'updateSubject' : ActorMethod<[SubjectId, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];