/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface StudyStats {
    completionRatePercent: bigint;
    totalMinutesThisWeek: bigint;
    sessionsToday: bigint;
}
export interface PomodoroSession {
    id: SessionId;
    completedAt: Timestamp;
    durationMinutes: bigint;
    assignmentId?: AssignmentId;
    subjectId?: SubjectId;
}
export type AssignmentId = bigint;
export interface Assignment {
    id: AssignmentId;
    completedAt?: Timestamp;
    title: string;
    assignmentType: AssignmentType;
    description: string;
    deadline: Timestamp;
    subjectId: SubjectId;
    priority: Priority;
    totalMinutesStudied: bigint;
    isComplete: boolean;
}
export type SessionId = bigint;
export type ClassId = bigint;
export type SubjectId = bigint;
export interface Subject {
    id: SubjectId;
    name: string;
    color: string;
}
export interface ScheduledClass {
    id: ClassId;
    startTime: string;
    dayOfWeek: bigint;
    durationMinutes: bigint;
    subjectId: SubjectId;
}
export enum AssignmentType {
    assignment = "assignment",
    exam = "exam"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export interface backendInterface {
    createAssignment(subjectId: SubjectId, title: string, description: string, deadline: Timestamp, assignmentType: AssignmentType, priority: Priority): Promise<Assignment>;
    createScheduledClass(subjectId: SubjectId, dayOfWeek: bigint, startTime: string, durationMinutes: bigint): Promise<ScheduledClass>;
    createSubject(name: string, color: string): Promise<Subject>;
    deleteAssignment(id: AssignmentId): Promise<boolean>;
    deleteScheduledClass(id: ClassId): Promise<boolean>;
    deleteSubject(id: SubjectId): Promise<boolean>;
    getAssignments(): Promise<Array<Assignment>>;
    getPomodoroSessions(): Promise<Array<PomodoroSession>>;
    getScheduledClasses(): Promise<Array<ScheduledClass>>;
    getStudyStats(): Promise<StudyStats>;
    getSubjects(): Promise<Array<Subject>>;
    logPomodoroSession(subjectId: SubjectId | null, assignmentId: AssignmentId | null, durationMinutes: bigint): Promise<PomodoroSession>;
    markAssignmentComplete(id: AssignmentId): Promise<boolean>;
    updateAssignment(id: AssignmentId, title: string, description: string, deadline: Timestamp, assignmentType: AssignmentType, priority: Priority): Promise<boolean>;
    updateSubject(id: SubjectId, name: string, color: string): Promise<boolean>;
}
import type { Assignment as _Assignment, AssignmentId as _AssignmentId, AssignmentType as _AssignmentType, PomodoroSession as _PomodoroSession, Priority as _Priority, SessionId as _SessionId, SubjectId as _SubjectId, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAssignment(arg0: SubjectId, arg1: string, arg2: string, arg3: Timestamp, arg4: AssignmentType, arg5: Priority): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Assignment_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, arg2, arg3, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Assignment_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createScheduledClass(arg0: SubjectId, arg1: bigint, arg2: string, arg3: bigint): Promise<ScheduledClass> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduledClass(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduledClass(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSubject(arg0: string, arg1: string): Promise<Subject> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubject(arg0, arg1);
            return result;
        }
    }
    async deleteAssignment(arg0: AssignmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return result;
        }
    }
    async deleteScheduledClass(arg0: ClassId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduledClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduledClass(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: SubjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async getAssignments(): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignments();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignments();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPomodoroSessions(): Promise<Array<PomodoroSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPomodoroSessions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPomodoroSessions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduledClasses(): Promise<Array<ScheduledClass>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledClasses();
            return result;
        }
    }
    async getStudyStats(): Promise<StudyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyStats();
            return result;
        }
    }
    async getSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects();
            return result;
        }
    }
    async logPomodoroSession(arg0: SubjectId | null, arg1: AssignmentId | null, arg2: bigint): Promise<PomodoroSession> {
        if (this.processError) {
            try {
                const result = await this.actor.logPomodoroSession(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PomodoroSession_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPomodoroSession(to_candid_opt_n18(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PomodoroSession_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAssignmentComplete(arg0: AssignmentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssignmentComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssignmentComplete(arg0);
            return result;
        }
    }
    async updateAssignment(arg0: AssignmentId, arg1: string, arg2: string, arg3: Timestamp, arg4: AssignmentType, arg5: Priority): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignment(arg0, arg1, arg2, arg3, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignment(arg0, arg1, arg2, arg3, to_candid_AssignmentType_n1(this._uploadFile, this._downloadFile, arg4), to_candid_Priority_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateSubject(arg0: SubjectId, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AssignmentType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentType): AssignmentType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PomodoroSession_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PomodoroSession): PomodoroSession {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssignmentId]): AssignmentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubjectId]): SubjectId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    completedAt: _Timestamp;
    durationMinutes: bigint;
    assignmentId: [] | [_AssignmentId];
    subjectId: [] | [_SubjectId];
}): {
    id: SessionId;
    completedAt: Timestamp;
    durationMinutes: bigint;
    assignmentId?: AssignmentId;
    subjectId?: SubjectId;
} {
    return {
        id: value.id,
        completedAt: value.completedAt,
        durationMinutes: value.durationMinutes,
        assignmentId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.assignmentId)),
        subjectId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.subjectId))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    completedAt: [] | [_Timestamp];
    title: string;
    assignmentType: _AssignmentType;
    description: string;
    deadline: _Timestamp;
    subjectId: _SubjectId;
    priority: _Priority;
    totalMinutesStudied: bigint;
    isComplete: boolean;
}): {
    id: AssignmentId;
    completedAt?: Timestamp;
    title: string;
    assignmentType: AssignmentType;
    description: string;
    deadline: Timestamp;
    subjectId: SubjectId;
    priority: Priority;
    totalMinutesStudied: bigint;
    isComplete: boolean;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        assignmentType: from_candid_AssignmentType_n8(_uploadFile, _downloadFile, value.assignmentType),
        description: value.description,
        deadline: value.deadline,
        subjectId: value.subjectId,
        priority: from_candid_Priority_n10(_uploadFile, _downloadFile, value.priority),
        totalMinutesStudied: value.totalMinutesStudied,
        isComplete: value.isComplete
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assignment: null;
} | {
    exam: null;
}): AssignmentType {
    return "assignment" in value ? AssignmentType.assignment : "exam" in value ? AssignmentType.exam : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PomodoroSession>): Array<PomodoroSession> {
    return value.map((x)=>from_candid_PomodoroSession_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AssignmentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): _AssignmentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectId | null): [] | [_SubjectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentId | null): [] | [_AssignmentId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssignmentType): {
    assignment: null;
} | {
    exam: null;
} {
    return value == AssignmentType.assignment ? {
        assignment: null
    } : value == AssignmentType.exam ? {
        exam: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
