/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// Do not edit manually.

import { createRootRoute } from "@tanstack/react-router";
import { Route as rootRouteImport } from "./routes/__root";
import { Route as AssignmentsImport } from "./routes/assignments";
import { Route as CalendarImport } from "./routes/calendar";
import { Route as IndexImport } from "./routes/index";
import { Route as SubjectsImport } from "./routes/subjects";
import { Route as TimerImport } from "./routes/timer";

const rootRoute = rootRouteImport;

const indexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const subjectsRoute = SubjectsImport.update({
  id: "/subjects",
  path: "/subjects",
  getParentRoute: () => rootRoute,
} as never);

const assignmentsRoute = AssignmentsImport.update({
  id: "/assignments",
  path: "/assignments",
  getParentRoute: () => rootRoute,
} as never);

const calendarRoute = CalendarImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRoute,
} as never);

const timerRoute = TimerImport.update({
  id: "/timer",
  path: "/timer",
  getParentRoute: () => rootRoute,
} as never);

export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof IndexImport;
    parentRoute: typeof rootRoute;
  };
  "/subjects": {
    id: "/subjects";
    path: "/subjects";
    fullPath: "/subjects";
    preLoaderRoute: typeof SubjectsImport;
    parentRoute: typeof rootRoute;
  };
  "/assignments": {
    id: "/assignments";
    path: "/assignments";
    fullPath: "/assignments";
    preLoaderRoute: typeof AssignmentsImport;
    parentRoute: typeof rootRoute;
  };
  "/calendar": {
    id: "/calendar";
    path: "/calendar";
    fullPath: "/calendar";
    preLoaderRoute: typeof CalendarImport;
    parentRoute: typeof rootRoute;
  };
  "/timer": {
    id: "/timer";
    path: "/timer";
    fullPath: "/timer";
    preLoaderRoute: typeof TimerImport;
    parentRoute: typeof rootRoute;
  };
}

export const routeTree = rootRoute.addChildren([
  indexRoute,
  subjectsRoute,
  assignmentsRoute,
  calendarRoute,
  timerRoute,
]);
